"""Remove unnecessary fields from Record table

Revision ID: bb88cd67e2f9
Revises: d42561488649
Create Date: 2024-08-16 15:46:07.375309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb88cd67e2f9'
down_revision = 'd42561488649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.drop_column('included_in_pool')
        batch_op.drop_column('date_last_spoken')
        batch_op.drop_column('talk_length')
        batch_op.drop_column('speaker_pos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('speaker_pos', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('talk_length', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('date_last_spoken', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('included_in_pool', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
