"""Add speaker_pos and talk_length fields to Record model

Revision ID: d42561488649
Revises: 
Create Date: 2024-08-09 08:33:16.246223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42561488649'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('speaker_pos', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('talk_length', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.drop_column('talk_length')
        batch_op.drop_column('speaker_pos')

    # ### end Alembic commands ###
